### ISSUE TITLE
Add some info to README about useful arguments to salt-ssh

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/opendataservices-deploy#4]
e.g.
http://docs.saltstack.com/en/latest/ref/states/testing.html
`--state-output=mixed`

**Comment by caprenter** [comment]
This is also a very old issue. Is there anything to be done?

**Comment by Bjwebb** [comment]
Yes, this info would still be useful to add to the README.

**Comment by idlemoor** [comment]
Grrr. Don't merge that yet, the formatting is bad :(
