### ISSUE TITLE
OCDSKingFisher - should salt scripts update .ssh/authorised_keys?

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/opendataservices-deploy#56]
We currently have some keys in a secret place but I don't think we have anywhere we actually write them to the server by salt!

(Given that a lot of people add keys by hand, maybe we don't want to?)

**Comment by robredpath** [comment]
@odscjames - see https://github.com/OpenDataServices/opendataservices-deploy/blob/98945633dde9de56daa587017207740f692e4835/salt/lib.sls#L35-L43 

No-one should be adding keys to any of our servers by hand apart from to solve the initial setup chicken and egg problem. Keys should be added to the secret place, and then highstate will put them in the right place on the server.

**Comment by odscjames** [comment]
Oh, this does cover it. I was confused because I couldn't see where a variable was being used - I was searching for the full name and couldn't find it because it was in the form "{{ user }}_authorized_keys ". Thanks.

**Comment by robredpath** [comment]
Yeah, I find it quite hard to search through salt code; I find the best way to navigate is to look for the name (or part name) of the file on disk that I'm looking for that doesn't include any variable substitution (eg authorized_keys) and work from there.

**Comment by odscjames** [comment]
> looking for that doesn't include any variable substitution

My problem was I didn't know there WAS variable substitution in this case :smile:
