### ISSUE TITLE
Change default_branch: 'live' to default_branch: 'master'

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/opendataservices-deploy#58]
For cove, we don't use 'live' branch any more.

https://github.com/OpenDataServices/opendataservices-deploy/blob/master/pillar/live_pillar.sls#L2 says live, but it's set to master in other pillar files.

So lets just change that line, to make it clear that it's the live branch.

TO DO: DOUBLE CHECK THIS FIRST

**Comment by Bjwebb** [comment]
We use the "live" branch again.
