### ISSUE TITLE
Kingfisher Dev has no Process Crons

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/opendataservices-deploy#69]
It's because of https://github.com/OpenDataServices/opendataservices-deploy/blob/master/salt/ocdskingfisherarchive.sls#L45 and onwards, the next 4 cron statements.

Why is this there - can it be removed?

**Comment by robredpath** [comment]
The commit that adds them is https://github.com/OpenDataServices/opendataservices-deploy/commit/774bd6fa68f6a890ad99bfd5513ba4a105d82339 - seemingly to explicitly remove the crons for the archive server. I would assume that this was intended to disable functionality that's not relevant on the archive server, never expecting all parts of kingfisher to run on one box (as happens on kingfisher dev).

**Comment by robredpath** [comment]
We probably don't need to run the archive component on dev, as it's pretty lightweight, but check with @kindly as I know he's been doing some work to make more use of the spare clock cycles on that box for views purposes.

**Comment by odscjames** [comment]
I've chatted with @kindly and am sorting this now
