### ISSUE TITLE
[2.1] OCP deployment of OCDS documentation

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/opendataservices-deploy#73]
* Create new standalone dev docs server. Ask for a OCP subdomain for this.
* Move dev site, resolving any issues in deploying process this creates
* Remove dev site from current server
* Create new standalone live docs server.
* Move live site, resolving any issues in deploying process this creates
* Remove live site from current server
* Add SSL to live site via Lets Encrypt

**Comment by odscjames** [comment]
This is done, apart from 
* the SSL, which is now handled in https://github.com/open-contracting/standard/issues/878
* adding Icinga to the new servers, which @idlemoor is looking at
