### ISSUE TITLE
Rename OCDS Kit Web to OCDS Toucan

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/opendataservices-deploy#78]
Should be served from http://toucan.open-contracting.org

Please also add a 301 redirect from ocdskit.open-contracting.org to toucan.open-contracting.org

**Comment by odscjames** [comment]
See https://trello.com/c/becHQKUG/15-move-remaining-servers-to-ocps-bytemark-account

**Comment by odscjames** [comment]
http://ocdskit.open-contracting.org/ redirects to http://toucan.open-contracting.org/ - done
