### ISSUE TITLE
Add SSL to OCDS Toucan (was OCDS Kit Web)

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/opendataservices-deploy#79]

**Comment by odscjames** [comment]
See https://trello.com/c/SggBe9Px/60-update-ocds-toucan-ocds-kit-web-deployment#

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add SSL to OCDS Toucan](https://trello.com/c/SggBe9Px/60-add-ssl-to-ocds-toucan)
