### ISSUE TITLE
Unicode Strings appear

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/opendataservices-deploy#81]
Sometimes, in Apache configs with SSL we get unicode strings in the ServerAlias:

     ServerAlias u'FQDN'

Apache does not error on this, but it also doesn't work in that it won't recognise it as a valid website. And I'm not sure what this will do to CertBot, tho I haven't seen any errors.

I have noticed this on the VM from my Mac, and that is salt-ssh 2019.2.0 (Fluorine) installed from repo http://repo.saltstack.com/apt/ubuntu/18.04/amd64/2019.2

**Comment by odscjames** [comment]
This currently causes problems on Live4 - the www. subdomain on our website breaks. Tho this problem may be worked around when we set up redirects, depending on how we do this.

**Comment by Bjwebb** [comment]
The problem is in the `apache` macro - https://github.com/OpenDataServices/opendataservices-deploy/blob/master/salt/lib.sls#L121 - this is rendered as a list by Jinja, which will insert the `u`s and then used as yaml, which doesn't ignore them. The solution is to use the `yaml` filter, ie.

```
        serveraliases: {{ serveraliases|yaml }}
```

**Comment by odscjames** [comment]
Thanks! I saw stuff in changelog Salt about this and would want to check this works on a good range of versions, tho, but I can test this.

**Comment by odscjames** [comment]
https://docs.saltstack.com/en/latest/topics/releases/2019.2.0.html#non-backward-compatible-change-to-yaml-renderer is the link I saw before that raised concerns for me.

**Comment by odscjames** [comment]
Extra info: this bug only happens if you pass a variable to the apache macro! If you pass actual content direct to the apache macro, it works fine.

**Comment by odscjames** [comment]
serveraliases: {{ serveraliases|yaml }}

Does seem to fix it. 

ps. I'm running salt-ssh 2019.2.0 (Fluorine)

**Comment by odscjames** [comment]
Pushed fix to master. Thanks @Bjwebb

**Comment by jpmckinney** [comment]
Should this change be replicated in OCP's deploy repo?

**Comment by odscjames** [comment]
I think so, but at least we should check - created https://github.com/open-contracting/deploy/issues/46
