### ISSUE TITLE
prometheus pillar warnings/errors

### ISSUE THREAD

**Issue by michaelwood** [OpenDataServices/opendataservices-deploy#82]
[server name] state.highstate
[ERROR   ] Specified SLS 'private.prometheus_pillar' in environment 'base' is not available on the salt master
[ERROR   ] Template was specified incorrectly: False
[CRITICAL] Pillar render error: Specified SLS 'private.prometheus_pillar' in environment 'base' is not available on the salt master
[WARNING ] /home/michael/dev/ods/opendataservices-deploy/venv/lib/python3.6/site-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)

[ERROR   ] Specified SLS 'private.prometheus_pillar' in environment 'base' is not available on the salt master
[ERROR   ] Template was specified incorrectly: False
[CRITICAL] Pillar render error: Specified SLS 'private.prometheus_pillar' in environment 'base' is not available on the salt master
[WARNING ] /home/michael/dev/ods/opendataservices-deploy/venv/lib/python3.6/site-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)

**Comment by odscjames** [comment]
Did you git pull in pillar/private (or use the https://github.com/OpenDataServices/opendataservices-deploy/blob/master/updateToMaster.sh script?)

**Comment by michaelwood** [comment]
Ah I can't remember, possibly not! I'll update and reopen if the problem persists. Cheers

**Comment by odscjames** [comment]
Yeah, the Prometheus variables are put on all machines, as that is what will happen eventually and there should be no downside. No actual salt tasks for Prometheus should be run on the 360 servers yet tho.
