### ISSUE TITLE
Re-using a uwsgi port causes issues

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/opendataservices-deploy#9]

**Comment by caprenter** [comment]
This issue is a month old and has no description.

I'm checking in as part of a Thursday round up.

@bjwebb any action you want to take on this (or schedule)?

**Comment by Bjwebb** [comment]
The issue is that when I use a new branch on a previously used port in https://github.com/OpenDataServices/opendataservices-deploy/blob/master/pillar/dev_pillar.sls#L15 there is some manual cleanup to be done. We should be able to automate this.

Currently I'm doing this infrequently enough that it's not high priority to automate.

**Comment by Bjwebb** [comment]
With 16.04 it's now possible to talk uswgi over unix sockets, avoiding this problem.
